{
  parserClass="com.github.nilsa.ideatestplugin.psi.NilsParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Nils"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.nilsa.ideatestplugin.psi.parser"
  psiImplPackage="com.github.nilsa.ideatestplugin.psi.parser.impl"

  elementTypeHolderClass="com.github.nilsa.ideatestplugin.psi.parser.NilsTypes"
  elementTypeClass="com.github.nilsa.ideatestplugin.psi.parser.NilsElementType"
  tokenTypeClass="com.github.nilsa.ideatestplugin.psi.parser.NilsTokenType"
}

nilsFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY